# Clippy configuration for ai-proxy-system

# Cognitive complexity threshold
cognitive-complexity-threshold = 30

# Type complexity threshold
type-complexity-threshold = 250

# Single char binding names threshold (corrected field name)
single-char-binding-names-threshold = 4

# Too many arguments threshold
too-many-arguments-threshold = 7

# Too many lines threshold
too-many-lines-threshold = 100

# Large types threshold (in bytes)
trivial-copy-size-limit = 64

# Enum variant name threshold
enum-variant-name-threshold = 3

# Literal representation threshold
literal-representation-threshold = 10

# Avoid breaking exported API
avoid-breaking-exported-api = false

# Allow expect and unwrap in tests
allow-expect-in-tests = true
allow-unwrap-in-tests = true

# Disallowed names (variables that should not be used)
disallowed-names = ["foo", "bar", "baz", "tmp"]

# Allowed scripts (for non-ASCII identifiers)
allowed-scripts = ["Latin"]