[package]
name = "api-proxy"
version = "0.1.0"
edition = "2021"
authors = ["AI Proxy Team"]
description = "Enterprise-grade AI service proxy platform"
license = "MIT"
repository = "https://github.com/your-org/api-proxy"
keywords = ["ai", "proxy", "rust", "pingora", "enterprise"]
categories = ["web-programming", "api-bindings"]
readme = "README.md"

# Workspace configuration (will be uncommented when sub-projects are created)
# [workspace]
# members = [
#     ".",
#     "migration",
#     "entity",
# ]

# Linting configuration
[lints.rust]
unsafe_code = "forbid"
missing_docs = "warn"
unused_imports = "warn"
unused_variables = "warn"
dead_code = "warn"

[lints.clippy]
all = { level = "warn", priority = -1 }
pedantic = { level = "warn", priority = -1 }
nursery = { level = "warn", priority = -1 }
cargo = { level = "warn", priority = -1 }
# Allow some pedantic lints that are too strict for our use case
module_name_repetitions = "allow"
missing_errors_doc = "allow"
missing_panics_doc = "allow"
cargo_common_metadata = "allow"

[dependencies]
# Core dependencies (will be added in next phases)
# pingora = "0.1"
# axum = "0.7"
# sea-orm = "0.12"
# redis = "0.24"
# tokio = { version = "1.0", features = ["full"] }
# serde = { version = "1.0", features = ["derive"] }
# thiserror = "1.0"
# anyhow = "1.0"

[dev-dependencies]
# Test dependencies (will be added in testing phase)
