# AI代理平台生产环境配置文件

# 双端口服务器配置
[dual_port]
workers = 4

# 管理服务配置
[dual_port.management]
enabled = true
route_prefixes = ["/api", "/admin"]

[dual_port.management.http]
host = "0.0.0.0"
port = 9090

[dual_port.management.access_control]
allowed_ips = ["0.0.0.0/0"]
denied_ips = []
require_auth = false
auth_methods = ["ApiKey"]

# CORS配置
[dual_port.management.cors]
enabled = true
origins = ["*"]

# 代理服务配置
[dual_port.proxy]
enabled = true
route_prefixes = ["/v1", "/proxy"]

[dual_port.proxy.http]
host = "0.0.0.0"
port = 8080

[dual_port.proxy.load_balancing]
strategy = "RoundRobin"
health_check_interval = 30
failure_threshold = 3
recovery_threshold = 2

# 启用的服务
[dual_port.enabled_services]
management = true
proxy = true
health_check = true
monitoring = true

# 数据库配置
[database]
url = "sqlite:///app/data/api-proxy.db"
max_connections = 10
connect_timeout = 30
query_timeout = 60

# 缓存配置
[cache]
cache_type = "memory"
memory_max_entries = 10000
default_ttl = 300
enabled = true

# Redis配置
[redis]
url = "redis://redis:6379"
pool_size = 10
host = "redis"
port = 6379
database = 0
password = ""
connection_timeout = 5
default_ttl = 3600
max_connections = 10

# 全局服务启用配置
[services]
management = true
proxy = true
health_check = true
monitoring = true

# 请求追踪配置
[trace]
enabled = true
default_trace_level = 0  # 生产环境默认基础追踪
sampling_rate = 0.1      # 生产环境10%采样率，减少性能影响
max_batch_size = 200     # 生产环境更大批量处理
flush_interval = 30      # 生产环境更长刷新间隔
timeout_seconds = 60     # 生产环境更长超时时间
async_write = true       # 异步写入
enable_phases = false    # 生产环境关闭阶段追踪以提升性能
enable_health_metrics = true  # 启用健康指标
enable_performance_metrics = false  # 生产环境关闭详细性能指标

# TLS配置（可选，用于HTTPS支持）
# [tls]
# cert_path = "/app/certs"
# acme_email = "admin@example.com"
# domains = ["example.com"]