# 生产环境配置 - 双端口分离架构

# 双端口服务器配置
[dual_port]
workers = 16

# 管理服务配置
[dual_port.management]
enabled = true
route_prefixes = ["/api", "/admin", "/"]

[dual_port.management.http]
host = "127.0.0.1"  # 生产环境建议限制为内网访问
port = 9090

[dual_port.management.access_control]
# 生产环境更严格的IP访问控制
allowed_ips = ["127.0.0.1/32", "::1/128", "10.0.0.0/8"]  # 仅允许本地和内网访问
denied_ips = []
require_auth = true
auth_methods = ["ApiKey", "JWT"]

# CORS配置
[dual_port.management.cors]
enabled = true
# 生产环境应该指定具体的源地址
origins = ["https://admin.your-domain.com", "https://dashboard.your-domain.com"]

# 代理服务配置
[dual_port.proxy]
enabled = true
route_prefixes = ["/v1", "/proxy"]

[dual_port.proxy.http]
host = "0.0.0.0"
port = 8080

[dual_port.proxy.load_balancing]
strategy = "HealthBest"
health_check_interval = 15
failure_threshold = 2
recovery_threshold = 3

# 启用的服务
[dual_port.enabled_services]
management = true
proxy = true
health_check = true
monitoring = true

[database]
url = "sqlite:./data/prod.db"
max_connections = 50
connect_timeout = 10
query_timeout = 60

[redis]
url = "redis://redis:6379"
pool_size = 50
host = "redis"
port = 6379
database = 0
connection_timeout = 10
default_ttl = 3600
max_connections = 50

[services]
management = true
proxy = true
health_check = true
monitoring = true