# 开发环境配置 - 双端口分离架构

# 双端口服务器配置
[dual_port]
workers = 4

# 管理服务配置
[dual_port.management]
enabled = true
route_prefixes = ["/api", "/admin", "/"]

[dual_port.management.http]
host = "0.0.0.0"
port = 9090

[dual_port.management.access_control]
allowed_ips = ["127.0.0.1/32", "::1/128", "192.168.0.0/16", "10.0.0.0/8", "172.16.0.0/12"]
denied_ips = []
require_auth = false
auth_methods = ["ApiKey"]

# CORS配置
[dual_port.management.cors]
enabled = true
# 允许的源地址列表，"*" 表示允许所有源
origins = ["*"]
# 或者指定具体的源地址：
# origins = ["http://localhost:3000", "http://127.0.0.1:3000", "https://your-domain.com"]

# 代理服务配置
[dual_port.proxy]
enabled = true
route_prefixes = ["/v1", "/proxy", "/gemini"]

[dual_port.proxy.http]
host = "0.0.0.0"
port = 8080

[dual_port.proxy.load_balancing]
strategy = "RoundRobin"
health_check_interval = 30
failure_threshold = 3
recovery_threshold = 2

# 启用的服务
[dual_port.enabled_services]
management = true
proxy = true
health_check = true
monitoring = true

# 数据库配置
[database]
url = "sqlite://./data/dev.db"
max_connections = 10
connect_timeout = 30
query_timeout = 30

# 缓存配置
[cache]
cache_type = "memory"
memory_max_entries = 10000
default_ttl = 300
enabled = true

# Redis配置
[redis]
url = "redis://127.0.0.1:6379/0"
pool_size = 10
host = "127.0.0.1"
port = 6379
database = 0
connection_timeout = 10
default_ttl = 3600
max_connections = 10

# OAuth 清理任务配置
[oauth_cleanup]
enabled = true
# pending 状态会话的过期时间（分钟）
pending_expire_minutes = 30
# 清理任务执行间隔（秒）
cleanup_interval_seconds = 300
# 单次清理的最大记录数
max_cleanup_records = 1000
# 删除已过期记录的保留天数
expired_records_retention_days = 7

