# 开发环境配置 - 基于基础config.toml的完整结构

# 双端口服务器配置
[dual_port]
workers = 4

# 管理服务配置 - 开发环境允许外部访问
[dual_port.management]

[dual_port.management.http]
host = "0.0.0.0"  # 开发环境允许外部访问
port = 9090

[dual_port.management.access_control]
allowed_ips = ["127.0.0.1/32", "::1/128"]
denied_ips = []

# 代理服务配置  
[dual_port.proxy]

[dual_port.proxy.http]
host = "0.0.0.0"
port = 8080

# 开发数据库配置
[database]
url = "sqlite://./data/dev.db"
max_connections = 10
connect_timeout = 30
query_timeout = 60

# 开发缓存配置
[cache]
cache_type = "memory"
memory_max_entries = 10000
default_ttl = 300

# 开发Redis配置
[redis]
url = "redis://localhost:6379"
pool_size = 10
host = "localhost"  
port = 6379
database = 0
connection_timeout = 5
default_ttl = 3600
max_connections = 10