# AI代理平台 - 简化配置

# 双端口架构基础配置
[dual_port]
[dual_port.management.http]
host = "127.0.0.1"  # 管理接口限制本地访问
port = 9090

[dual_port.proxy.http]
host = "0.0.0.0"    # 代理接口开放访问
port = 8080

# 必需的数据存储配置
[database]
url = "sqlite://./data/api_proxy.db"

[redis]
url = "redis://127.0.0.1:6379/0"

