# 生产环境配置 - 基于基础config.toml的完整结构

# 双端口服务器配置 - 生产环境更多工作线程
[dual_port]
workers = 16

# 管理服务配置 - 生产环境安全配置
[dual_port.management]

[dual_port.management.http]
host = "0.0.0.0"  # 生产环境仅本地访问
port = 9090

[dual_port.management.access_control]
allowed_ips = []  # 包含私网段
denied_ips = []

# 代理服务配置  
[dual_port.proxy]

[dual_port.proxy.http]
host = "0.0.0.0"
port = 8080

# 生产数据库配置 - 更高的连接数和更短的超时
[database]
url = "sqlite://./data/prod.db"
max_connections = 50
connect_timeout = 10
query_timeout = 60

# 生产缓存配置 - 更大的缓存
[cache]
cache_type = "memory"
memory_max_entries = 50000
default_ttl = 300
