# 生产环境配置

[server]
host = "0.0.0.0"
port = 80
https_port = 443
workers = 16

[database]
url = "sqlite:./data/prod.db"
max_connections = 50
connect_timeout = 10
query_timeout = 60

[redis]
url = "redis://redis:6379"
pool_size = 50

[tls]
cert_path = "/etc/ssl/certs"
acme_email = "admin@yourdomain.com"
domains = ["api.yourdomain.com", "yourdomain.com"]