# 生产环境配置

[server]
host = "0.0.0.0"
port = 80
https_port = 443
workers = 16

[database]
url = "sqlite:./data/prod.db"
max_connections = 50
connect_timeout = 10
query_timeout = 60

[redis]
url = "redis://redis:6379"
pool_size = 50
host = "redis"
port = 6379
database = 0
connection_timeout = 10
default_ttl = 3600
max_connections = 50

[services]
management = true
proxy = true
health_check = true
monitoring = true