# 默认配置 - 继承自 config.dev.toml

[server]
host = "0.0.0.0"
port = 8080
https_port = 8443
workers = 8

[database]
url = "sqlite:./data/proxy.db"
max_connections = 20
connect_timeout = 30
query_timeout = 30

[redis]
url = "redis://localhost:6379"
pool_size = 20

[tls]
cert_path = "./certs"
acme_email = "admin@yourdomain.com"
domains = ["yourdomain.com"]