name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  backend:
    runs-on: ubuntu-latest
    environment: DOCKERHUB
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Login to Aliyun Container Registry
        uses: docker/login-action@v3
        with:
          registry: registry.cn-hangzhou.aliyuncs.com
          username: ${{ secrets.ALIYUN_USERNAME }}
          password: ${{ secrets.ALIYUN_TOKEN }}

      - name: Set image tags
        id: tags-backend
        run: |
          echo "dockerhub_latest=${{ secrets.DOCKERHUB_USERNAME }}/proxybackend:latest" >> $GITHUB_OUTPUT
          echo "aliyun_latest=registry.cn-hangzhou.aliyuncs.com/luciferzl/proxybackend:latest" >> $GITHUB_OUTPUT
          echo "cache_ref=${{ secrets.DOCKERHUB_USERNAME }}/proxybackend:buildcache" >> $GITHUB_OUTPUT
          
      - name: Build and push backend
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ steps.tags-backend.outputs.dockerhub_latest }}
            ${{ steps.tags-backend.outputs.aliyun_latest }}
          cache-from: type=registry,ref=${{ steps.tags-backend.outputs.cache_ref }}
          cache-to: type=registry,ref=${{ steps.tags-backend.outputs.cache_ref }},mode=max

  frontend:
    runs-on: ubuntu-latest
    environment: DOCKERHUB
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Login to Aliyun Container Registry
        uses: docker/login-action@v3
        with:
          registry: registry.cn-hangzhou.aliyuncs.com
          username: ${{ secrets.ALIYUN_USERNAME }}
          password: ${{ secrets.ALIYUN_TOKEN }}

      - name: Set image tags
        id: tags-frontend
        run: |
          echo "dockerhub_latest=${{ secrets.DOCKERHUB_USERNAME }}/proxyfrontend:latest" >> $GITHUB_OUTPUT
          echo "aliyun_latest=registry.cn-hangzhou.aliyuncs.com/luciferzl/proxyfrontend:latest" >> $GITHUB_OUTPUT
          echo "cache_ref=${{ secrets.DOCKERHUB_USERNAME }}/proxyfrontend:buildcache" >> $GITHUB_OUTPUT
          
      - name: Build and push frontend
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ steps.tags-frontend.outputs.dockerhub_latest }}
            ${{ steps.tags-frontend.outputs.aliyun_latest }}
          cache-from: type=registry,ref=${{ steps.tags-frontend.outputs.cache_ref }}
          cache-to: type=registry,ref=${{ steps.tags-frontend.outputs.cache_ref }},mode=max